version: '3.3'

services:
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DELETE_RETENTION_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always

  kafka_daily_reporter:
    build:
      context: ./kafka_daily_reporter
      dockerfile: Dockerfile
    volumes:
      - ./data/daily_reports/:/app/data/
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      START_DATE: 01/01/2030
      END_DATE: 31/01/2030
      DAY_SIMULATION_INTERVAL_SECONDS: 1
    depends_on:
      - kafka
      - zookeeper

  locations_information_system:
    build:
      context: ./api_controller
      dockerfile: Dockerfile
    volumes:
      - ./data/datalake/locations/:/app/data/
    ports:
      - "8081:8081"

  sun_energy_information_system:
    build:
      context: ./api_controller
      dockerfile: Dockerfile
    volumes:
      - ./data/datalake/sun_energy/:/app/data/
    ports:
      - "8082:8081"

  wind_energy_information_system:
    build:
      context: ./api_controller
      dockerfile: Dockerfile
    volumes:
      - ./data/datalake/wind_energy/:/app/data/
    ports:
      - "8083:8081"

  water_energy_information_system:
    build:
      context: ./api_controller
      dockerfile: Dockerfile
    volumes:
      - ./data/datalake/water_energy/:/app/data/
    ports:
      - "8084:8081"

  geo_energy_information_system:
    build:
      context: ./api_controller
      dockerfile: Dockerfile
    volumes:
      - ./data/datalake/geo_energy/:/app/data/
    ports:
      - "8085:8081"

  coal_energy_information_system:
    build:
      context: ./api_controller
      dockerfile: Dockerfile
    volumes:
      - ./data/datalake/coal_energy/:/app/data/
    ports:
      - "8086:8081"

#  kafka_consumer_check:
#    build:
#      context: ./kafka_consumer_check
#      dockerfile: Dockerfile
#    environment:
#      KAFKA_HOST: kafka
#      KAFKA_PORT: 9092
#    depends_on:
#      - kafka
#      - zookeeper
